

# This file was *autogenerated* from the file makeEisenJson.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)#!/usr/local/src/SageMath/sage
import json
import sys
import functionPile as fP



if(len(sys.argv) != _sage_const_3 ):
    print("Please run this script as 'python3 eisenCoeffMaker.py k N'")
    exit()
k = int(sys.argv[_sage_const_1 ])
N = int(sys.argv[_sage_const_2 ])

print(json.dumps(fP.genJson(k,N),indent=_sage_const_1 ))

